module.exports = {
  "PAGE_ACCESS_TOKEN": "EAAFGfXbOZAeQBAFRPjhGC0KuI5ZAZBN4F06omgJuIBDtym1m3TyCRe9T0xStfJleNwqdry4CyIdQVcojqkqpCca1WqP70WRpQMXEV3J7qSdqYgvZCEIFZA69DyZBf2gQMuQCfYZAukXkoL1MwZBTbky0S2MMm7z3vJAZAWyvxoCQP8FZB6hkhGghmR",  
  "VERIFY_TOKEN": "samplebot"
}  